#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

#AutoStart Apps 
sxhkd &
lxappearence &
picom --daemon --backend glx --vsync --config /dev/null &
nitrogen --restore &
dunst & 
polybar &
exec --no-startup-id /usr/lib/pam_kwallet_init
XDG_CURRENT_DESKTOP="KDE" /usr/lib/xdg-desktop-portal-kde &
XDG_CURRENT_DESKTOP="KDE" /usr/lib/xdg-desktop-portal &

