#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5  
bspc config top_padding		 36
bspc config border_width         0
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

#AutoStart Apps
 
polybar &
sxhkd &
lxappearence &
picom --daemon --backend glx --vsync --config /dev/null &
#picom &
nitrogen --restore &
dunst & 
exec --no-startup-id /usr/lib/pam_kwallet_init &
xsetroot -cursor_name left_ptr & 
nm-applet &
/home/eli/.config/polybar/launch.sh
fcitx5 &
./qtfilepicker.sh

# Open Firefox in desktop 1
bspc rule -a Firefox desktop='^1'

# Open Vesktop in desktop 2
bspc rule -a Vesktop desktop='^2'

# Open Kitty terminal in desktop 3
bspc rule -a kitty desktop='^3'

# Open Spotify in desktop 4
bspc rule -a spotify-launcher desktop='^4' 
